server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: ${DBMS_CONNECTION}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "PW9y7+1LUqVTnaW/HnUEBgEZta2vSa97uXyAziYa8egOy+va6T1PawD6KerNUiUK"
  valid-duration: 12
  refresh-duration: 24
