server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/spring_db"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "PW9y7+1LUqVTnaW/HnUEBgEZta2vSa97uXyAziYa8egOy+va6T1PawD6KerNUiUK"
  valid-duration: 12
  refresh-duration: 24
