server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://mysql-8.0.36:3306/spring_db}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "PW9y7+1LUqVTnaW/HnUEBgEZta2vSa97uXyAziYa8egOy+va6T1PawD6KerNUiUK"
  valid-duration: 12
  refresh-duration: 24
